username=nanthakumaransenthil@gmail.com
password=Nantha@2000
newcontent= Automation test engineer at cognizant technology solutions and skilled in Selenium, Java, Testng, Cucumber, JIRA, Webdriver, Maven,Jenkins, API, Github, Bitbucket
newcontentalt=Automation test engineer at cognizant technology solutions and skilled in Selenium, Java,TestNg, Cucumber, JIRA, WebDriver, Maven,Jenkins, Github, Bitbucket, API